# Generated by Django 4.0.5 on 2022-07-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.PositiveIntegerField(default=0)),
                ('full_name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('address1', models.CharField(default='', max_length=150)),
                ('address2', models.CharField(blank=True, max_length=150, null=True)),
                ('zipcode', models.CharField(default='', max_length=10)),
                ('city', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Unpaid', max_length=100)),
                ('payment_method', models.CharField(default='Credit Card', max_length=100)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('discount', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=0, editable=False, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='incomplete', max_length=50)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'OrderItem',
            },
        ),
        migrations.CreateModel(
            name='StripeIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=50, unique=True)),
                ('client_secret', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('paid', 'paid'), ('canceled', 'canceled'), ('refunded', 'refunded'), ('disputed', 'disputed'), ('partial refunded', 'partial refunded'), ('incomplete', 'incomplete')], default='incomplete', max_length=100)),
            ],
            options={
                'verbose_name': 'StripeIntent',
                'verbose_name_plural': 'StripeIntent',
            },
        ),
    ]
